default: &default
  pool: 5
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: homepagedev

test:
  <<: *default
  database: homepagetest

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
