default: &default
  pool: 5
  adapter: postgresql
  encoding: unicode
  username: homepage
  password: homepagepsql

development:
  <<: *default
  database: homepagedev

test:
  <<: *default
  database: homepagetest

production:
  <<: *default
  database: db/production.sqlite3
