# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb6c6c3054cd6499cb5253270b30606f757a5f414077634423ea2d789e8fb38ac2d1935baf52a4102b6068c137443dc5602d8bc4ecf7736b47a5223679e03890

test:
  secret_key_base: 2499466bb90b5ac89378d4068065401840e3ef73061bce97738f414963805211d8b862b8c32ad9d74379b89e1bbdd2d3406d61916e81d6b1286e1626c6eb512b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
